### ISSUE TITLE
Not an issue but request

### ISSUE THREAD

**Issue by toastedplease** [toasted-nutbread/yomichan-pitch-accent-dictionary#1]
Sorry I don't know anything about coding etc. but I really love your pitch accent display for yomichan. I was wondering if there was a way to use this to mass generate an anki deck. For example:

Front: audio of a word from yomichan
-------------------------------------------
Back: your pitch accent graph

The goal of this would be to train pitch accent recognition. 

Again very sorry for contacting you like this, I could not find any other way. I would really appreciate it if you could help me out.

Thank you and sorry once again.

**Comment by toasted-nutbread** [comment]
The best method will be to update Yomichan to support exporting pitch accent information, which is currently not supported. I'll see if I can work towards adding support.

FooSoft/yomichan#468

**Comment by toastedplease** [comment]
Thank you very much. I really appreciate every thing you are doing and it is really helpful. Thank you.

**Comment by toastedplease** [comment]
Hi toasted, I really appreciate this. Forgive my ignorance, but how to make it work? I copy pasted 
ext/bg/data/default-anki-field-templates.handlebars into the template under Yomichan options, however it says Error: Missing helper: "op" 

Thanks!

**Comment by toasted-nutbread** [comment]
You will have to use version 20.8.3.0, which the testing release is currently on. If you wait a few days, that version will soon be promoted to the stable release. ([More info](https://github.com/FooSoft/yomichan#installation))

After that, you can use the default field templates and just select one of the pitch-accent options for the Anki fields.
![image](https://user-images.githubusercontent.com/11037431/89676967-90053b00-d8ba-11ea-8b7e-b58f3a1a288b.png)

**Comment by toastedplease** [comment]
Thank you so much. Your help has been invaluable. If there is any way to support you please let me know. Thanks so much.

**Comment by toasted-nutbread** [comment]
Just be sure to report any [issues](https://github.com/FooSoft/yomichan/issues) you find and whatnot. Cheers.
